name: Update Changelog

on:
  push:
    tags:
      - 'v*'  # Runs when a version tag is pushed (e.g., v0.421)

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch full history for tags and branches

    - name: Set Git user information
      run: |
        git config --global user.email "shane@acemedia.ninja"
        git config --global user.name "AceMedia"

    - name: Get commit messages
      run: git log --pretty=format:"* %s" `git describe --tags --abbrev=0`..HEAD > commits.txt

    - name: Append commit messages to changelog
      run: |
        echo "== Changelog ==" >> readme.txt
        cat commits.txt >> readme.txt
        git add readme.txt
        git commit -m "Update changelog in readme"

    - name: Checkout the main branch
      run: |
        git fetch origin
        git checkout main  # Checkout main branch explicitly

    - name: Push changes to the main branch
      run: git push origin main
