name: Generate Changelog

on:
  push:
    tags:
      - 'v*'  # Runs when a version tag is pushed (e.g., v1.0.0)

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch full history to capture all commits

    - name: Set Git user information
      run: |
        git config --global user.email "github-actions-bot@users.noreply.github.com"
        git config --global user.name "GitHub Actions Bot"

    - name: Generate changelog based on commit history
      run: |
        git log --no-merges --pretty=format:"%h %s" > changelog.txt
        cat changelog.txt

    - name: Append changelog to CHANGELOG.md
      run: |
        echo "## Version $GITHUB_REF - $(date +'%Y-%m-%d')" >> CHANGELOG.md
        cat changelog.txt >> CHANGELOG.md
        echo "" >> CHANGELOG.md
        git add CHANGELOG.md
        git commit -m "Update CHANGELOG.md for $GITHUB_REF"

    - name: Push changes back to repository
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub Actions token automatically available
      run: |
        git push origin main
