name: Generate Changelog

on:
  push:
    tags:
      - 'v*'  # Runs when a version tag is pushed (e.g., v1.0.0)

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: main  # Checkout the main branch
        fetch-depth: 0  # Fetch full history to capture all commits

    - name: Set Git user information
      run: |
        git config --global user.email "github-actions-bot@users.noreply.github.com"
        git config --global user.name "GitHub Actions Bot"

    - name: Ensure CHANGELOG.md exists
      run: |
        if [ ! -f CHANGELOG.md ]; then
          echo "# Changelog" > CHANGELOG.md
        fi

    - name: Generate changelog based on commit history
      run: |
        version="${GITHUB_REF#refs/tags/}"
        timestamp=$(date +"%Y-%m-%d %H:%M:%S")
        new_changelog="## Version $version - **$timestamp**\n\n$(git log --no-merges --pretty=format:'* _%h_ - **%cd** - %s' --date=format:'%Y-%m-%d %H:%M:%S')\n"

        # Check if the changelog already contains this version
        if grep -q "## Version $version" CHANGELOG.md; then
          # Replace the old changelog for this version
          sed -i "/## Version $version/,/^$/c\\$new_changelog" CHANGELOG.md
        else
          # Append the new changelog after the "# Changelog" title
          sed -i '/# Changelog/a\'"$new_changelog" CHANGELOG.md
        fi

    - name: Commit and push changes
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git add CHANGELOG.md
        git commit -m "Update CHANGELOG.md for $GITHUB_REF"
        git pull origin main  # Ensure you're up to date before pushing
        git push https://$GH_PAT@github.com/${{ github.repository }} main  # Push using PAT
